### ISSUE TITLE
Temp .cs file not found, analyser throws exception

### ISSUE THREAD

**Issue by realvizu** [realvizu/NsDepCop#1]
Happens on projects that contain MS workflow designer.
Confirmed that the temp .cs file really does not exist on the given path (so not a permission problem).

Snippet from the build output:

```
26>MSBUILD : error NSDEPCOPEX: [NsDepCop] System.IO.FileNotFoundException: Could not find file 'C:\Users\ferenc.vizkeleti\AppData\Local\Temp\ku41wvbl.cs'.
26>MSBUILD : error NSDEPCOPEX: File name: 'C:\Users\ferenc.vizkeleti\AppData\Local\Temp\ku41wvbl.cs'
26>MSBUILD : error NSDEPCOPEX:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
26>MSBUILD : error NSDEPCOPEX:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
26>MSBUILD : error NSDEPCOPEX:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
26>MSBUILD : error NSDEPCOPEX:    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseFile(String path, CSharpParseOptions options, CancellationToken cancellationToken)
26>MSBUILD : error NSDEPCOPEX:    at Codartis.NsDepCop.Core.Analyzer.Roslyn.DependencyAnalyzer.<AnalyzeProject>b__2(String i)
26>MSBUILD : error NSDEPCOPEX:    at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
26>MSBUILD : error NSDEPCOPEX:    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
26>MSBUILD : error NSDEPCOPEX:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
26>MSBUILD : error NSDEPCOPEX:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
26>MSBUILD : error NSDEPCOPEX:    at Codartis.NsDepCop.Core.Analyzer.Roslyn.DependencyAnalyzer.<AnalyzeProject>d__4.MoveNext()
26>MSBUILD : error NSDEPCOPEX:    at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.Execute()
```

**Comment by realvizu** [comment]
Source and metadata load errors now handled gracefully.
