### ISSUE TITLE
ystem.ArgumentException: Should not be null or whitespace.

### ISSUE THREAD

**Issue by mcintyre321** [realvizu/NsDepCop#20]
We're trying to use NsDepCop in a VS2017 solution inside a traditional-style csproj console app.

here's our config:
```
<?xml version="1.0" encoding="utf-8"?>
<NsDepCopConfig IsEnabled="true" CodeIssueKind="Warning" ChildCanDependOnParentImplicitly="true" InheritanceDepth="1">
    <Allowed From="*" To="*" />
    <Disallowed From="MyProgram.Runner.Domain" To="MyProgram.Runner.Adapters" />
</NsDepCopConfig>
```
Although NsDepCop appears to work correctly (i.e. warnings appear if we violate the rules), there is also an error, which causes the build to fail. Do you know what might be wrong? thanks

```
Exception during NsDepCopTask execution: System.ArgumentException: Should not be null or whitespace.
Parameter name: fromTypeName
   at Codartis.NsDepCop.Core.Interface.Analysis.TypeDependency..ctor(String fromNamespaceName, String fromTypeName, String toNamespaceName, String toTypeName, SourceSegment sourceSegment)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.SyntaxNodeTypeDependencyEnumerator.CreateTypeDependency(ITypeSymbol fromType, ITypeSymbol toType, SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.SyntaxNodeTypeDependencyEnumerator.<GetTypeDependencies>d__1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.TypeDependencyEnumeratorSyntaxVisitor.VisitGenericName(GenericNameSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.TypeDependencyEnumeratorSyntaxVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitDelegateDeclaration(DelegateDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.DelegateDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.TypeDependencyEnumeratorSyntaxVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.TypeDependencyEnumeratorSyntaxVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.TypeDependencyEnumeratorSyntaxVisitor.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Roslyn.RoslynTypeDependencyEnumerator.<GetTypeDependencies>d__3.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__24`1.MoveNext()
   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.ReportIllegalDependencies(IEnumerable`1 illegalDependencies, IssueKind issueKind, Int32 maxIssueCount)
   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.ExecuteAnalysis(IDependencyAnalyzer dependencyAnalyzer, String configFolderPath)
   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.Execute()	CrossBrandJobPoster.Runner			
```

**Comment by realvizu** [comment]
It seems like a bug. The analyzer should not try to validate types without a name but apparently it does. Do you have any idea what code snippet may cause it, so I can reproduce the problem?

**Comment by realvizu** [comment]
I've attempted to fix it "in the blind" (without a repro).
@mcintyre321 can you try it please?
Here's the build (prerelease NuGet package):
https://ci.appveyor.com/api/buildjobs/92pgdlc54aepq03l/artifacts/source%2FNsDepCop.NuGet%2Fbin%2FRelease%2FNsDepCop.1.6.1-rc1.nupkg

**Comment by mcintyre321** [comment]
Great, thanks! I'll give that a go in a moment. We're using c#7 named ValueTuples, and named delegates as parameters and return types if that helps.

**Comment by mcintyre321** [comment]
That fixed it, thanks! 

We've just copied the dlls into our packages folder for now, it would be great if could you let me know when a new package is pushed.

**Comment by realvizu** [comment]
@mcintyre321 It's live now:
https://www.nuget.org/packages/NsDepCop/1.6.1
